# permissions for end users to edit cloudproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-operator
    app.kubernetes.io/part-of: cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudprovider-editor-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/status
  verbs:
  - get
