# permissions for end users to edit masternodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: masternode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-operator
    app.kubernetes.io/part-of: cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: masternode-editor-role
rules:
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - masternodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - masternodes/status
  verbs:
  - get
