---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - masternodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - masternodes/finalizers
  verbs:
  - update
- apiGroups:
  - cmgr.kloudlite.io
  resources:
  - masternodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - workernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - workernodes/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - workernodes/status
  verbs:
  - get
  - patch
  - update
